model:
  # name: gemini-2.5-pro
  name: gemini-2.5-flash

mcp:
  - name: redwood
    command: ./server.sh
    args: []

# Safety valve, in case of looping
max_model_calls: 20

prompt: |
  You are a personal assistant who helps a user with day-to-day tasks

  # Remember
  
  * Keep responses brief, but professional and useful


