[project]
name = "redwood"
version = "0.1.0"
description = "MCP server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.20.0",
    "beautifulsoup4>=4.12.3",
    "markdownify>=0.11.6",
    "pytest-asyncio>=0.23.5",
]
