[project]
name = "redwood"
version = "0.1.0"
description = "MCP server"
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.20.0",
    "beautifulsoup4>=4.12.3",
    "markdownify>=0.11.6",
    "pytest-asyncio>=0.23.5",
    "fastmcp>=2.14.1",
    "munch>=4.0.0",
    "google-genai>=1.56.0",
    "diskcache>=5.6.3",
    "pathvalidate>=3.3.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
cli = "cli:run"
server = "server:run"
